#!/bin/sh
# Regenerate rtl/index.qip: every RTL file the core needs, in a stable order.
# Run from the repo root whenever a file is added or removed.
set -e
out=rtl/index.qip
{
echo "# =============================================================================="
echo "# Super Sprint core RTL -- generated by tools/gen_qip.sh, do not edit"
echo "# =============================================================================="
echo 'set_global_assignment -name SEARCH_PATH [file join $::quartus(qip_path) ""]'
echo 'set_global_assignment -name SYSTEMVERILOG_FILE [file join $::quartus(qip_path) "ssprint_pkg.sv"]'
for f in $(cd rtl && ls *.sv t11/*.sv 2>/dev/null | grep -v ssprint_pkg.sv | sort); do
    echo "set_global_assignment -name SYSTEMVERILOG_FILE [file join \$::quartus(qip_path) \"$f\"]"
done
echo ""
echo "# T65 6502 (BSD, Daniel Wallner / MikeJ), GHDL-converted"
echo 'set_global_assignment -name VERILOG_FILE [file join $::quartus(qip_path) "../modules/cpu-t65/gen/t65.v"]'
echo "# jt51 YM2151 (GPL-3, Jose Tejada)"
for f in $(cd modules/sound-jt51/hdl && ls *.v | sort); do
    echo "set_global_assignment -name VERILOG_FILE [file join \$::quartus(qip_path) \"../modules/sound-jt51/hdl/$f\"]"
done
} > $out
echo "wrote $out ($(grep -c FILE $out) files)"
